#!/usr/bin/env python3
"""Generate the LaTeX snippet that integrates the parameter-sweep figure into the paper.

Reads results/param_sweeps.csv (scripts/param_sweeps.py) and emits results/param_sweeps_snippet.tex:
  1. the \\figure environment for fig5_param_sweeps.pdf, with a caption stating the exclusion /
     hollow-marker / ordinal-axis conventions;
  2. a rewritten opening paragraph for Section 5.3 (Sensitivity and Runtime) that folds the s,
     |B|, and report findings in alongside the existing xi sentence;
  3. the table* surgery: tab:xi-sweep is removed from the two-minipage float, leaving
     tab:traceability as a standalone table.

All figures quoted in the prose are read from the CSV, not hand-transcribed, so re-running the
sweep and this script keeps the paper's numbers in sync with the data.

  python3 scripts/write_param_sweeps_snippet.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent


def _row(df, sweep, value, dataset):
    m = df[(df["sweep"] == sweep) & (df["value"].astype(str) == str(value)) & (df["dataset"] == dataset)]
    return m.iloc[0] if len(m) else None


def _f1(df, sweep, value, dataset) -> float | None:
    r = _row(df, sweep, value, dataset)
    return None if r is None else float(r["mean_f1"])


def _fmt(v: float | None, nd: int = 3) -> str:
    return "?" if v is None else f"{v:.{nd}f}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--param-sweeps-csv", type=Path, default=ROOT / "results" / "param_sweeps.csv")
    ap.add_argument("--out", type=Path, default=ROOT / "results" / "param_sweeps_snippet.tex")
    args = ap.parse_args()

    df = pd.read_csv(args.param_sweeps_csv)
    df["dataset"] = df["dataset"].astype(str).str.lower()

    def pair(sweep, value, field="mean_f1"):
        """(Ceravolo, Ostovar) value at one sweep point, as formatted strings."""
        out = []
        for ds in ("ceravolo", "ostovar"):
            r = _row(df, sweep, value, ds)
            out.append(None if r is None or pd.isna(r[field]) else float(r[field]))
        return out

    def comparable(sweep, value, ds) -> bool:
        """False when that cell was excluded from the figure for having too few testable
        boundaries -- the prose must not quote a number the figure deliberately withholds."""
        r = _row(df, sweep, value, ds)
        return r is not None and (pd.isna(r["n_boundaries"]) or r["n_boundaries"] >= 4)

    # |B|: where does each metric peak, over the cells that are actually comparable?
    b_values = [25, 50, 100, 150, 200, 300]
    best_lag_b = {}
    for ds in ("ceravolo", "ostovar"):
        cand = [(float(_row(df, "B", v, ds)["mean_lag"]), v) for v in b_values
                if comparable("B", v, ds) and _row(df, "B", v, ds) is not None
                and pd.notna(_row(df, "B", v, ds)["mean_lag"])]
        if cand:
            best_lag_b[ds] = min(cand)[1]

    # report policies ranked by summed mean lag across both datasets
    report_lags = {}
    for pol in ("start", "mid", "end", "adaptive", "refine"):
        vals = [v for v in pair("report", pol, "mean_lag") if v is not None]
        if vals:
            report_lags[pol] = sum(vals) / len(vals)
    best_pol = min(report_lags, key=report_lags.get) if report_lags else "end"
    worst_pol = max(report_lags, key=report_lags.get) if report_lags else "start"

    f1_s1, f1_s2 = pair("s", 1), pair("s", 2)
    lag_s1, lag_s2 = pair("s", 1, "mean_lag"), pair("s", 2, "mean_lag")
    f1_b25, f1_b100 = pair("B", 25), pair("B", 100)
    lag_b25, lag_b100 = pair("B", 25, "mean_lag"), pair("B", 100, "mean_lag")
    f1_rep = {p: pair("report", p) for p in ("start", "end")}

    # ---- exclusion notes (n_boundaries < 4) for the caption ----
    exclusions = []
    for sweep in ("s", "B"):
        for ds in ("ceravolo", "ostovar"):
            sub = df[(df["sweep"] == sweep) & (df["dataset"] == ds)].copy()
            if sub.empty:
                continue
            sub["_v"] = pd.to_numeric(sub["value"], errors="coerce")
            sub = sub.sort_values("_v")
            bad = sub[sub["n_boundaries"] < 4]
            if len(bad):
                exclusions.append(f"{ds} at {sweep}$\\geq${bad['_v'].min():g}")

    tex = f"""%% === Auto-generated by scripts/write_param_sweeps_snippet.py from results/param_sweeps.csv ===
%% Integration instructions:
%%  1. Insert the \\begin{{figure}}...\\end{{figure}} block below into Section 5 (Evaluation),
%%     immediately before \\subsection{{Sensitivity and Runtime}} (sec:sensitivity).
%%  2. Replace the opening paragraph of that subsection (the one starting "DeclareCascade uses a
%%     single fixed configuration...") with the REPLACEMENT PARAGRAPH below.
%%  3. In the existing \\begin{{table*}}...\\end{{table*}} float (label tab:traceability /
%%     tab:xi-sweep), delete the second \\begin{{minipage}}...\\end{{minipage}} (tab:xi-sweep) and
%%     the \\hfill before it, per the TABLE SURGERY note below -- tab:traceability then stands
%%     alone in the float.

%% ---------------------------------------------------------------------------
%% 1. New figure
%% ---------------------------------------------------------------------------
\\begin{{figure}}[t]
\\centering
\\includegraphics[width=\\textwidth]{{figures/fig5_param_sweeps.pdf}}
\\caption{{Mean F1 (top) and mean localisation error (bottom, Avg-Lag in cases) across four
one-at-a-time sweeps of the detection configuration: the intensity threshold $\\xi$, the
trailing-window width $s$, the batch size $|B|$, and the localisation policy. All other
parameters are held at the default (dashed guide, bold tick). $x$ axes are ordinal -- swept
values are equally spaced, so segment slope is not a derivative. A line is cut where fewer than
four boundaries remain statistically testable ({'; '.join(exclusions) if exclusions else 'none in this run'}),
since an F1 computed over that few candidate boundaries is not meaningful; a hollow lag marker
denotes a mean Avg-Lag computed over fewer than 60\\% of logs, since \\texttt{{get\\_avg\\_lag}}
only averages logs with at least one true positive and a config that stops detecting reports the
lag of the few logs it still hits.}}
\\label{{fig:param-sweeps}}
\\end{{figure}}

%% ---------------------------------------------------------------------------
%% 2. Replacement opening paragraph for Section 5.3 (Sensitivity and Runtime)
%% ---------------------------------------------------------------------------
DeclareCascade uses a single fixed configuration ($\\vartheta\\!=\\!0.999$, $\\xi\\!=\\!0.01$,
$s\\!=\\!1$, $|B|\\!=\\!100$, report$\\,=\\,$end) across both datasets without per-dataset tuning.
Figure~\\ref{{fig:param-sweeps}} extends the sensitivity analysis from $\\xi$ to the other three
detection parameters, sweeping each while holding the rest at that default.
%
The intensity threshold $\\xi$ has a clear optimum at the chosen value: F1 is stable within
$\\xi\\in[0.005,\\,0.02]$ and falls away on both sides, as noise dominates at lower thresholds
(Ostovar {_fmt(_f1(df,'xi',0.0,'ostovar'))} at $\\xi\\!=\\!0$) and recall collapses at higher ones
({_fmt(_f1(df,'xi',0.10,'ostovar'))} at $\\xi\\!=\\!0.10$, over only
{int(_row(df,'xi',0.10,'ostovar')['logs_with_tp'])} of
{int(_row(df,'xi',0.10,'ostovar')['n_logs'])} logs).
%
The trailing window admits no such latitude: $s\\!=\\!1$ is strictly best, and widening it to
$s\\!=\\!2$ costs accuracy immediately (Ceravolo {_fmt(f1_s1[0])}$\\rightarrow${_fmt(f1_s2[0])},
Ostovar {_fmt(f1_s1[1])}$\\rightarrow${_fmt(f1_s2[1])}) while inflating localisation error roughly
an order of magnitude ({_fmt(lag_s1[0],1)}$\\rightarrow${_fmt(lag_s2[0],1)} and
{_fmt(lag_s1[1],1)}$\\rightarrow${_fmt(lag_s2[1],1)} cases). A wider trailing window both re-tests
inside the same transition, re-firing on a drift it has already reported, and -- on a
1\\,000-case log -- leaves too few boundaries statistically testable to judge at all.
%
The batch size $|B|$ exposes the granularity/power trade-off directly. Shrinking it does
\\emph{{not}} buy better localisation as one might expect: at $|B|\\!=\\!25$ both F1 and lag
degrade (Ceravolo {_fmt(f1_b25[0])} at {_fmt(lag_b25[0],1)} cases, versus {_fmt(f1_b100[0])} at
{_fmt(lag_b100[0],1)} at the default), because 25-case batches make the per-batch proportions too
noisy and the detector fires early and spuriously. Growing it past the default costs lag
outright, the reported change point being quantised to a coarser batch edge. The lag optimum sits
at $|B|\\!=\\!{best_lag_b.get('ceravolo', 100)}$ (Ceravolo) and
$|B|\\!=\\!{best_lag_b.get('ostovar', 100)}$ (Ostovar), close to the default.
%
The five localisation policies, finally, separate cleanly from the other three parameters: F1 is
essentially flat across all of them (Ceravolo {_fmt(f1_rep['start'][0])} for \\emph{{start}} vs
{_fmt(f1_rep['end'][0])} for \\emph{{end}}) while mean lag varies by more than an order of
magnitude, from {_fmt(report_lags.get(best_pol),1)} cases (\\emph{{{best_pol}}}) to
{_fmt(report_lags.get(worst_pol),1)} (\\emph{{{worst_pol}}}, averaged over both datasets). This is
exactly what Section~\\ref{{sec:confirmation}} claims structurally: the policy is applied after
confirmation and changes only \\emph{{where}} inside the firing batch a detected change is
reported, never \\emph{{which}} batches fire.

%% ---------------------------------------------------------------------------
%% 3. TABLE SURGERY (existing table* float, currently tab:traceability + tab:xi-sweep)
%% ---------------------------------------------------------------------------
%% DELETE this second minipage (and the preceding \\hfill) from the existing \\begin{{table*}}:
%%
%%   \\hfill
%%   \\begin{{minipage}}[c]{{0.4\\textwidth}}
%%   ...
%%   \\label{{tab:xi-sweep}}
%%   \\end{{minipage}}
%%
%% tab:traceability then stands alone; widen its minipage from 0.58\\textwidth to, e.g.,
%% 0.9\\textwidth (or drop the minipage wrapper entirely and let the tabularx span the table*).
"""

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(tex)
    print(tex)
    print(f"\nWrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
